### ISSUE TITLE
Post summaries to slack?

### ISSUE THREAD

**Issue by swiggumj** [dlakaplan/LogParse#21]
I think you mentioned this before @dlakaplan. Would it be straightforward to set up a flag to post to  pulsars.slack.com (#observations) as a part of my cron job?

**Comment by dlakaplan** [comment]
Yes.  The only issue is that you need an API key that can’t be stored on GitHub.  So this would need to be set as a local file or in your BASH environment.  Doable, but needs to be done right.

**Comment by dlakaplan** [comment]
Check CGCA #testing channel.   Pushed up as ba2f929.  Seems to work, but there could be other enhancements/issues.

**Comment by dlakaplan** [comment]
Closed for now
